name: Create tag from SBT

on:
  push:
    branch: tagging

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Get most recent tag
      uses: "WyriHaximus/github-action-get-previous-tag@master"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - name: Setup Scala
      uses: olafurpg/setup-scala@v5
    - name: Get SBT version
      id: current_version
      run: echo "::set-output name=current_version::$(sbt version | tail -n 1 | awk '{print $2}')"
    - name: Print version
      if: ${{ steps.current_version.outputs.current_version == '0.4.1' }}
      run: echo "Current version is ${{ steps.current_version.outputs.current_version }}"
    - name: Create tag
      if: ${{ steps.current_version.outputs.current_version == '0.4.1' }}
      uses: richardsimko/update-tag@master
      with:
        tag_name: ${{ steps.current_version.outputs.current_version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
