name: Create tag

on:
  push:
    branch: tagging

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get previous tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@master"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    - uses: olafurpg/setup-scala@v5
    - name: Get SBT version
      run: sbt version | tail -n 1 | awk '{print $2}'

    # - name: Upload JAR
    #   id: upload-jar
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./target/scala-2.12/flyway-awslambda-${{ steps.tag_name.outputs.tag }}.jar
    #     asset_name: flyway-awslambda-${{ steps.tag_name.outputs.tag }}.jar
    #     asset_content_type: application/java-archive
