name: Create tag

on:
  push:
    branch: tagging

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    # - name: Get previous tag
    #   run: "git describe --tags $(git rev-list --tags --max-count=1)"
    - uses: olafurpg/setup-scala@v5
    - name: Get SBT version
      id: current_version
      run: echo "::set-output name=current_version::$(sbt version | tail -n 1 | awk '{print $2}')"
    - name: Print version
      if: ${{ steps.current_version.outputs.current_version == "0.4.1" }}"
      run: echo "Current version is ${{ steps.current_version.outputs.current_version }}"
    # - name: Upload JAR
    #   id: upload-jar
    #   uses: actions/upload-release-asset@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     upload_url: ${{ steps.create_release.outputs.upload_url }}
    #     asset_path: ./target/scala-2.12/flyway-awslambda-${{ steps.tag_name.outputs.tag }}.jar
    #     asset_name: flyway-awslambda-${{ steps.tag_name.outputs.tag }}.jar
    #     asset_content_type: application/java-archive
